# Generated by Django 5.1.2 on 2024-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="API Key"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="base_url",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="Base URL"
            ),
        ),
    ]
