# Generated by Django 5.1.2 on 2024-12-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_rename_name_modelconfiguration_model"),
        ("user", "0002_customuser_api_key_customuser_base_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="base_url",
        ),
        migrations.AddField(
            model_name="customuser",
            name="model_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai.modelconfiguration",
                verbose_name="Model Configuration",
            ),
        ),
    ]
