# Generated by Django 5.1.2 on 2024-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_customuser_base_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="custom_base_url",
            field=models.URLField(
                blank=True, max_length=512, null=True, verbose_name="Custom Base URL"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="custom_model_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Custom Model Name"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="model_selection_status",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Model"),
                    ("default", "Default Model"),
                    ("none", "No Model Selected"),
                ],
                default="none",
                max_length=10,
                verbose_name="Model Selection Status",
            ),
        ),
    ]
