# Generated by Django 5.1.2 on 2024-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_customuser_custom_base_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="model_selection_status",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Model"),
                    ("default", "Default Model"),
                    ("none", "No Model Selected"),
                ],
                default="default",
                max_length=10,
                verbose_name="Model Selection Status",
            ),
        ),
    ]
