# Generated by Django 5.1.2 on 2024-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_model_selection_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="model_selection_status",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Model"),
                    ("default", "Default Model"),
                    ("select", "Select"),
                ],
                default="default",
                max_length=10,
                verbose_name="Model Selection Status",
            ),
        ),
    ]
