# Generated by Django 5.1.2 on 2024-11-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mindmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mindmap",
            name="is_del",
            field=models.BooleanField(default=False),
        ),
    ]
